name: docker

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
  schedule:
    - cron:  '0 20 * * 0'

defaults:
  run:
    shell: bash

jobs:

  docker:
    name: Docker publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2.2.1
        with:
          images: mozgiii/netloc
          tag-sha: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:master
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: "!github.event.pull_request"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          # TODO: add 32-bit platforms after the fs emulation bug is fixed in QEMU.
          # Ref: https://bugs.launchpad.net/qemu/+bug/1805913
          # TODO: add other platforms once rust docker image supports them.
          platforms: linux/amd64,linux/arm64
          push: ${{!github.event.pull_request }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
